/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx.h"


int main(void)
{


 }
void usart2_tx_init(void)
{
	//PD5 USART2_TX
	//PD6 USART2_RX
	//Enable clock access to GPIOD
	RCC->AHB1ENR = RCC_AHB1ENR_GPIODEN;

	//Set PD5 mode to alternate function mode
	GPIOD_MODER |= GPIO_MODER_MODE5_1;
	GPIOD_MODER &= ~GPIO_MODER_MODE5_1;

	//Set PD5 alternate function type to USART_TX
	GPIOD->AFR[0] |= GPIO_AFRL_AFRL5_0;
	GPIOD->AFR[0] |= GPIO_AFRL_AFRL5_1;
	GPIOD->AFR[0] |= GPIO_AFRL_AFRL5_2;
	GPIOD->AFR[0] &= ~GPIO_AFRL_AFRL5_3;
}

void usart(void)
{
	/*configure usart module*/
	//Enable clock access to usart2
	RCC->APB1ENR |= RCC_APB1ENR_USART2EN;

	//Configure baudrate

}
